MutableInt
public Integer getValue()
public void setValue(final int value)
public void setValue(final Number value)
public void increment()
public void decrement()
public void add(final int operand)
public void add(final Number operand)
public void subtract(final int operand)
public void subtract(final Number operand)
public int intValue()
public long longValue()
public float floatValue()
public double doubleValue()
public Integer toInteger()
public boolean equals(final Object obj)
public int hashCode()
public int compareTo(final MutableInt other)
public String toString()
