/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 04:14:29 GMT 2021
 */

package org.apache.commons.lang3.text;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.text.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      char[] charArray0 = new char[7];
      String string0 = WordUtils.uncapitalize(" 4sF`|2a_?<0?w", charArray0);
      assertEquals(" 4sF`|2a_?<0?w", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = WordUtils.wrap("w\ni\nl\n!\nR\nZ\n_\n<\n1\n#\nD", (-2779), "6.0", true);
      assertEquals("w6.0\n6.0i6.0\n6.0l6.0\n6.0!6.0\n6.0R6.0\n6.0Z6.0\n6.0_6.0\n6.0<6.0\n6.016.0\n6.0#6.0\n6.0D", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = WordUtils.wrap("", 99, "", true);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      char[] charArray0 = new char[4];
      String string0 = WordUtils.uncapitalize("", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = WordUtils.uncapitalize((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = WordUtils.swapCase("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = WordUtils.initials((String) null, (char[]) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = WordUtils.initials((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = WordUtils.initials("szr+A7Qf!F_1;I");
      assertEquals("s", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalizeFully("", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("C");
      assertEquals("C", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      char[] charArray0 = new char[5];
      String string0 = WordUtils.capitalize((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = WordUtils.capitalize((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = WordUtils.capitalize("';.hakb(vx~y");
      assertEquals("';.hakb(vx~y", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      char[] charArray0 = new char[8];
      String string0 = WordUtils.wrap("VYoR'Q]DXC.]J.nI", (-180), "^^+Ha77:)gARnl^eta+^+Ha77:)gARnl^etaH^+Ha77:)gARnl^etaa^+Ha77:)gARnl^eta7^+Ha77:)gARnl^eta7^+Ha77:)gARnl^eta:^+Ha77:)gARnl^eta)^+Ha77:)gARnl^eta^+Ha77:)gARnl^etag^+Ha77:)gARnl^etaA^+Ha77:)gARnl^etaR^+Ha77:)gARnl^etan^+Ha77:)gARnl^etal^+Ha77:)gARnl^eta^^+Ha77:)gARnl^etae^+Ha77:)gARnl^etat^+Ha77:)gARnl^etaa", true);
      // Undeclared exception!
      WordUtils.initials(string0, charArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = WordUtils.initials("", (char[]) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = WordUtils.uncapitalize((String) null, (char[]) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      char[] charArray0 = new char[6];
      String string0 = WordUtils.capitalizeFully((String) null, charArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalize("", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = WordUtils.capitalize("%,NT", (char[]) null);
      assertEquals("%,NT", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = WordUtils.wrap("|RY cXvuKn^,$~6S", (-5), "", false);
      assertEquals("|RYcXvuKn^,$~6S", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = WordUtils.wrap("wil!RZ_<1#D", (-1125), (String) null, true);
      assertEquals("w\ni\nl\n!\nR\nZ\n_\n<\n1\n#\nD", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String string0 = WordUtils.wrap((String) null, 3323, "wil!RZ_<1#D", true);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[0] = ')';
      String string0 = WordUtils.capitalize("X%Pxg;:+!l)-0!", charArray0);
      assertEquals("X%Pxg;:+!l)-0!", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = WordUtils.initials("}>r dv1#", (char[]) null);
      assertEquals("}d", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.initials("y>:3]{v_{+6", charArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String string0 = WordUtils.swapCase("'<4Z?");
      assertEquals("'<4z?", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String string0 = WordUtils.swapCase((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String string0 = WordUtils.swapCase("java.awt.graphicsenv");
      assertEquals("JAVA.AWT.GRAPHICSENV", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("}>r Dv1#", (char[]) null);
      assertEquals("}>r dv1#", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("6k9meQ!ze>6`^");
      assertEquals("6k9meQ!ze>6`^", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.uncapitalize("Y>:3]{V_{+6", charArray0);
      assertEquals("Y>:3]{V_{+6", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalizeFully("G=vyOu;'}", charArray0);
      assertEquals("G=vyOu;'}", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      char[] charArray0 = new char[4];
      String string0 = WordUtils.capitalizeFully("R`k7_l=dhbyd", charArray0);
      assertEquals("R`k7_l=dhbyd", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("}>r Dv1#", (char[]) null);
      assertEquals("}>r Dv1#", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      char[] charArray0 = new char[0];
      String string0 = WordUtils.capitalize("Y>:3]{V_{+6", charArray0);
      assertEquals("Y>:3]{V_{+6", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      String string0 = WordUtils.wrap("}>r Dv1#", (-53));
      assertEquals("}>r\nDv1#", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      String string0 = WordUtils.wrap("Pp_>H?BqR !1^", 3, "java.awt.graphicsenv", true);
      assertEquals("Pp_java.awt.graphicsenv>H?java.awt.graphicsenvBqRjava.awt.graphicsenv!1^", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      String string0 = WordUtils.wrap(" gsF`|2a_?nj?{", (-1), ".=@.|)u#p`EX_LhZi", true);
      assertEquals("g.=@.|)u#p`EX_LhZis.=@.|)u#p`EX_LhZiF.=@.|)u#p`EX_LhZi`.=@.|)u#p`EX_LhZi|.=@.|)u#p`EX_LhZi2.=@.|)u#p`EX_LhZia.=@.|)u#p`EX_LhZi_.=@.|)u#p`EX_LhZi?.=@.|)u#p`EX_LhZin.=@.|)u#p`EX_LhZij.=@.|)u#p`EX_LhZi?.=@.|)u#p`EX_LhZi{", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = WordUtils.wrap((String) null, 3);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      String string0 = WordUtils.initials("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      WordUtils wordUtils0 = new WordUtils();
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      String string0 = WordUtils.wrap("", (-1));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      String string0 = WordUtils.uncapitalize("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      String string0 = WordUtils.capitalizeFully("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      String string0 = WordUtils.capitalize("");
      assertEquals("", string0);
  }
}
