/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 12 14:13:00 GMT 2022
 */

package org.apache.commons.lang3.mutable;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.mutable.MutableDouble;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MutableDouble_ESTest extends MutableDouble_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      MutableDouble mutableDouble1 = new MutableDouble();
      mutableDouble0.add(592.901071187011);
      boolean boolean0 = mutableDouble0.equals(mutableDouble1);
      assertEquals((byte)80, mutableDouble0.byteValue());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      Float float0 = new Float(2041.1075058674);
      mutableDouble0.subtract((Number) float0);
      assertEquals((-2042.1075439453125), mutableDouble0.toDouble(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble("0.0");
      assertEquals((byte)0, mutableDouble0.byteValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      mutableDouble0.increment();
      mutableDouble0.toDouble();
      assertEquals(1.0F, mutableDouble0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      mutableDouble0.setValue(0.0);
      mutableDouble0.toDouble();
      assertEquals(0.0, mutableDouble0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-469.632));
      Double double0 = mutableDouble0.toDouble();
      assertEquals((-469.632), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      long long0 = mutableDouble0.longValue();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(1.0);
      long long0 = mutableDouble0.longValue();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      mutableDouble0.setValue(1578.9262693);
      int int0 = mutableDouble0.intValue();
      assertEquals(1578, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Float float0 = new Float((-12.6));
      MutableDouble mutableDouble0 = new MutableDouble((Number) float0);
      int int0 = mutableDouble0.intValue();
      assertEquals((-12), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      mutableDouble0.setValue(1578.9262693);
      Double double0 = mutableDouble0.getValue();
      assertEquals(1578.9262693, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-534.208788));
      Double double0 = mutableDouble0.getValue();
      assertEquals((-534.208788), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      mutableDouble0.increment();
      float float0 = mutableDouble0.floatValue();
      assertEquals(1.0, mutableDouble0.getValue(), 0.01);
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      mutableDouble0.subtract(1.0);
      float float0 = mutableDouble0.floatValue();
      assertEquals((-1.0), mutableDouble0.getValue(), 0.01);
      assertEquals((-1.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(6.543);
      mutableDouble0.setValue(0.0);
      double double0 = mutableDouble0.doubleValue();
      assertEquals(0.0F, mutableDouble0.floatValue(), 0.01F);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(1.0);
      double double0 = mutableDouble0.doubleValue();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(1.0);
      MutableDouble mutableDouble1 = new MutableDouble((-748.4067104));
      int int0 = mutableDouble0.compareTo(mutableDouble1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-534.208788));
      MutableDouble mutableDouble1 = new MutableDouble(mutableDouble0);
      Float float0 = new Float((-534.208788));
      mutableDouble1.add((Number) float0);
      int int0 = mutableDouble1.compareTo(mutableDouble0);
      assertEquals((short) (-1068), mutableDouble1.shortValue());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      // Undeclared exception!
      try { 
        mutableDouble0.subtract((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableDouble", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(0.0);
      // Undeclared exception!
      try { 
        mutableDouble0.setValue((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableDouble", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Double double0 = new Double((-383.1516831584));
      MutableDouble mutableDouble0 = new MutableDouble((Number) double0);
      // Undeclared exception!
      try { 
        mutableDouble0.compareTo((MutableDouble) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableDouble", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      // Undeclared exception!
      try { 
        mutableDouble0.add((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableDouble", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MutableDouble mutableDouble0 = null;
      try {
        mutableDouble0 = new MutableDouble((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MutableDouble mutableDouble0 = null;
      try {
        mutableDouble0 = new MutableDouble((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableDouble", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      double double0 = mutableDouble0.doubleValue();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      MutableDouble mutableDouble1 = new MutableDouble((-489.35109671));
      boolean boolean0 = mutableDouble0.equals(mutableDouble1);
      assertFalse(boolean0);
      assertFalse(mutableDouble1.equals((Object)mutableDouble0));
      assertEquals((-489.35109671), mutableDouble1.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      boolean boolean0 = mutableDouble0.equals(mutableDouble0);
      assertTrue(boolean0);
      assertEquals((-1.0), mutableDouble0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      Object object0 = new Object();
      boolean boolean0 = mutableDouble0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      Double double0 = mutableDouble0.getValue();
      assertEquals(0.0, (double)double0, 0.01);
      
      MutableDouble mutableDouble1 = new MutableDouble((Number) double0);
      assertTrue(mutableDouble1.equals((Object)mutableDouble0));
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      mutableDouble0.decrement();
      assertEquals((-2.0), mutableDouble0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      String string0 = mutableDouble0.toString();
      assertEquals("-1.0", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      Double double0 = mutableDouble0.toDouble();
      assertEquals((-1.0), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-14.831459754745751));
      mutableDouble0.hashCode();
      assertEquals((-14.831459754745751), mutableDouble0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-14.831459754745751));
      long long0 = mutableDouble0.longValue();
      assertEquals((-14L), long0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(0.0);
      mutableDouble0.isNaN();
      assertEquals(0.0, mutableDouble0.toDouble(), 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      int int0 = mutableDouble0.intValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(0.0);
      Double double0 = mutableDouble0.getValue();
      assertEquals(0.0, (double)double0, 0.01);
      
      mutableDouble0.setValue((Number) double0);
      assertEquals("0.0", mutableDouble0.toString());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble(0.0);
      int int0 = mutableDouble0.compareTo(mutableDouble0);
      assertEquals(0, int0);
      assertEquals(0.0F, mutableDouble0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MutableDouble mutableDouble0 = null;
      try {
        mutableDouble0 = new MutableDouble("*6?@s3J");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble();
      float float0 = mutableDouble0.floatValue();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MutableDouble mutableDouble0 = new MutableDouble((-1.0));
      mutableDouble0.isInfinite();
      assertEquals("-1.0", mutableDouble0.toString());
  }
}
