/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 12 14:07:16 GMT 2022
 */

package org.apache.commons.lang3.mutable;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.mutable.MutableFloat;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MutableFloat_ESTest extends MutableFloat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      MutableFloat mutableFloat1 = new MutableFloat();
      mutableFloat1.decrement();
      boolean boolean0 = mutableFloat1.equals(mutableFloat0);
      assertEquals((-1.0F), mutableFloat1.floatValue(), 0.01F);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.decrement();
      assertEquals((-1.0F), mutableFloat0.floatValue(), 0.01F);
      
      mutableFloat0.subtract((Number) mutableFloat0);
      assertEquals("0.0", mutableFloat0.toString());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat("287.0");
      assertEquals(287.0F, mutableFloat0.getValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.add(1575.9F);
      mutableFloat0.toFloat();
      assertEquals("1575.9", mutableFloat0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat(1190.3407F);
      Byte byte0 = new Byte((byte)0);
      mutableFloat0.setValue((Number) byte0);
      mutableFloat0.toFloat();
      assertEquals(0.0F, mutableFloat0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-3220.7F));
      mutableFloat0.setValue(3455.5F);
      long long0 = mutableFloat0.longValue();
      assertEquals(3455.5, mutableFloat0.doubleValue(), 0.01);
      assertEquals(3455L, long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.decrement();
      long long0 = mutableFloat0.longValue();
      assertEquals((-1.0F), mutableFloat0.toFloat(), 0.01F);
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      int int0 = mutableFloat0.intValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.add(1575.9F);
      int int0 = mutableFloat0.intValue();
      assertEquals(1575L, mutableFloat0.longValue());
      assertEquals(1575, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      Byte byte0 = new Byte((byte) (-1));
      mutableFloat0.setValue((Number) byte0);
      Float float0 = mutableFloat0.getValue();
      assertEquals((-1.0F), (float)float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.increment();
      mutableFloat0.getValue();
      assertEquals(1.0F, mutableFloat0.getValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.subtract((-667.189F));
      float float0 = mutableFloat0.floatValue();
      assertEquals(667.189F, mutableFloat0.getValue(), 0.01F);
      assertEquals(667.189F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.subtract((-1191.0F));
      MutableFloat mutableFloat1 = new MutableFloat(0.0F);
      int int0 = mutableFloat0.compareTo(mutableFloat1);
      assertEquals(1191.0F, mutableFloat0.toFloat(), 0.01F);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      MutableFloat mutableFloat1 = new MutableFloat();
      mutableFloat0.decrement();
      int int0 = mutableFloat0.compareTo(mutableFloat1);
      assertEquals((-1.0F), mutableFloat0.toFloat(), 0.01F);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      // Undeclared exception!
      try { 
        mutableFloat0.subtract((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableFloat", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      // Undeclared exception!
      try { 
        mutableFloat0.setValue((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableFloat", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      // Undeclared exception!
      try { 
        mutableFloat0.compareTo((MutableFloat) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableFloat", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-4770.942F));
      // Undeclared exception!
      try { 
        mutableFloat0.add((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableFloat", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MutableFloat mutableFloat0 = null;
      try {
        mutableFloat0 = new MutableFloat((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MutableFloat mutableFloat0 = null;
      try {
        mutableFloat0 = new MutableFloat((Number) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.mutable.MutableFloat", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      MutableFloat mutableFloat1 = new MutableFloat();
      mutableFloat0.decrement();
      boolean boolean0 = mutableFloat1.equals(mutableFloat0);
      assertEquals((short) (-1), mutableFloat0.shortValue());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      boolean boolean0 = mutableFloat0.equals(mutableFloat0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      boolean boolean0 = mutableFloat0.equals("KtHa");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-3223.9314F));
      String string0 = mutableFloat0.toString();
      assertEquals("-3223.9314", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-3223.9314F));
      mutableFloat0.hashCode();
      assertEquals((-3223.9314F), mutableFloat0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      double double0 = mutableFloat0.doubleValue();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.decrement();
      double double0 = mutableFloat0.doubleValue();
      assertEquals((byte) (-1), mutableFloat0.byteValue());
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      Long long0 = new Long((byte) (-1));
      mutableFloat0.add((Number) long0);
      assertEquals((-1.0F), mutableFloat0.toFloat(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-3223.9314F));
      Float float0 = mutableFloat0.toFloat();
      assertEquals((-3223.9314F), (float)float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.subtract((Number) mutableFloat0);
      assertEquals(0.0F, mutableFloat0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      Float float0 = mutableFloat0.getValue();
      assertEquals(0.0F, (float)float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Float float0 = new Float((-2.317804F));
      MutableFloat mutableFloat0 = new MutableFloat((Number) float0);
      int int0 = mutableFloat0.intValue();
      assertEquals((-2), int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      mutableFloat0.increment();
      double double0 = mutableFloat0.doubleValue();
      assertEquals(1.0F, mutableFloat0.floatValue(), 0.01F);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      float float0 = mutableFloat0.floatValue();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      boolean boolean0 = mutableFloat0.isInfinite();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat((-3223.9314F));
      mutableFloat0.add((-3223.9314F));
      Float float0 = mutableFloat0.toFloat();
      assertEquals((-6447.863F), (float)float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      MutableFloat mutableFloat0 = null;
      try {
        mutableFloat0 = new MutableFloat("");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      boolean boolean0 = mutableFloat0.isNaN();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      Byte byte0 = new Byte((byte) (-1));
      mutableFloat0.setValue((Number) byte0);
      float float0 = mutableFloat0.floatValue();
      assertEquals((-1.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      long long0 = mutableFloat0.longValue();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MutableFloat mutableFloat0 = new MutableFloat();
      int int0 = mutableFloat0.compareTo(mutableFloat0);
      assertEquals(0, int0);
  }
}
