 String format(long millis)
 String format(Date date)
 String format(Calendar calendar)
 StringBuffer format(long millis, StringBuffer buf)
 StringBuffer format(Date date, StringBuffer buf)
 StringBuffer format(Calendar calendar, StringBuffer buf)
 String getPattern()
 TimeZone getTimeZone()
 Locale getLocale()
 StringBuffer format(Object obj, StringBuffer toAppendTo, FieldPosition pos)
