/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 12 13:10:29 GMT 2022
 */

package org.apache.commons.lang3.concurrent;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.IllegalFormatConversionException;
import java.util.UnknownFormatConversionException;
import java.util.concurrent.ThreadFactory;
import org.apache.commons.lang3.concurrent.BasicThreadFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThread;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BasicThreadFactory_ESTest extends BasicThreadFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.reset();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.daemon(true);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      Thread thread0 = MockThread.currentThread();
      Thread thread1 = basicThreadFactory0.newThread(thread0);
      assertTrue(thread1.isDaemon());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      Thread.UncaughtExceptionHandler thread_UncaughtExceptionHandler0 = MockThread.getDefaultUncaughtExceptionHandler();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.uncaughtExceptionHandler(thread_UncaughtExceptionHandler0);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      ThreadGroup threadGroup0 = (ThreadGroup)basicThreadFactory0.getUncaughtExceptionHandler();
      assertEquals("Test_Execution_Group", threadGroup0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.namingPattern("|");
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      MockThread mockThread0 = new MockThread("hh'X");
      basicThreadFactory0.newThread(mockThread0);
      long long0 = basicThreadFactory0.getThreadCount();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.priority(0);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Integer integer0 = basicThreadFactory0.getPriority();
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.priority(1);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Integer integer0 = basicThreadFactory0.getPriority();
      assertEquals(1, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.priority((-1));
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Integer integer0 = basicThreadFactory0.getPriority();
      assertEquals((-1), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.namingPattern("1~Xo7N-eu");
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      String string0 = basicThreadFactory0.getNamingPattern();
      assertEquals("1~Xo7N-eu", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.namingPattern("");
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      String string0 = basicThreadFactory0.getNamingPattern();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      basicThreadFactory_Builder0.daemon(true);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      Boolean boolean0 = basicThreadFactory0.getDaemonFlag();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.daemon(false);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Boolean boolean0 = basicThreadFactory0.getDaemonFlag();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.namingPattern("!B_ oZ%");
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      // Undeclared exception!
      try { 
        basicThreadFactory0.newThread((Runnable) null);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = '%'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      MockThread mockThread0 = new MockThread();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.namingPattern(",m<evtRjf1L%4ABU");
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      // Undeclared exception!
      try { 
        basicThreadFactory0.newThread(mockThread0);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // a != java.lang.Long
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      Boolean boolean0 = basicThreadFactory0.getDaemonFlag();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      ThreadFactory threadFactory0 = basicThreadFactory0.getWrappedFactory();
      assertNotNull(threadFactory0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      String string0 = basicThreadFactory0.getNamingPattern();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      Integer integer0 = basicThreadFactory0.getPriority();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      Thread.UncaughtExceptionHandler thread_UncaughtExceptionHandler0 = basicThreadFactory0.getUncaughtExceptionHandler();
      assertNull(thread_UncaughtExceptionHandler0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      // Undeclared exception!
      try { 
        basicThreadFactory_Builder0.uncaughtExceptionHandler((Thread.UncaughtExceptionHandler) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Uncaught exception handler must not be null!
         //
         verifyException("org.apache.commons.lang3.concurrent.BasicThreadFactory$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      // Undeclared exception!
      try { 
        basicThreadFactory_Builder0.namingPattern((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Naming pattern must not be null!
         //
         verifyException("org.apache.commons.lang3.concurrent.BasicThreadFactory$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      // Undeclared exception!
      try { 
        basicThreadFactory_Builder0.wrappedFactory((ThreadFactory) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Wrapped ThreadFactory must not be null!
         //
         verifyException("org.apache.commons.lang3.concurrent.BasicThreadFactory$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.priority(1);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Thread thread0 = MockThread.currentThread();
      basicThreadFactory0.newThread(thread0);
      assertEquals(1, (int)basicThreadFactory0.getPriority());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      Thread.UncaughtExceptionHandler thread_UncaughtExceptionHandler0 = MockThread.getDefaultUncaughtExceptionHandler();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.uncaughtExceptionHandler(thread_UncaughtExceptionHandler0);
      Thread thread0 = MockThread.currentThread();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      Thread thread1 = basicThreadFactory0.newThread(thread0);
      assertFalse(thread1.isInterrupted());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.wrappedFactory(basicThreadFactory0);
      BasicThreadFactory basicThreadFactory1 = basicThreadFactory_Builder1.build();
      assertEquals(0L, basicThreadFactory1.getThreadCount());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder0.build();
      long long0 = basicThreadFactory0.getThreadCount();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BasicThreadFactory.Builder basicThreadFactory_Builder0 = new BasicThreadFactory.Builder();
      BasicThreadFactory.Builder basicThreadFactory_Builder1 = basicThreadFactory_Builder0.priority(0);
      BasicThreadFactory basicThreadFactory0 = basicThreadFactory_Builder1.build();
      MockThread mockThread0 = new MockThread();
      // Undeclared exception!
      try { 
        basicThreadFactory0.newThread(mockThread0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.Thread", e);
      }
  }
}
