 static void setAccessibleWorkaround(final AccessibleObject o)
 static boolean isPackageAccess(final int modifiers)
 static boolean isAccessible(final Member m)
 static int compareParameterTypes(final Class<?>[] left, final Class<?>[] right, final Class<?>[] actual)
private static float getTotalTransformationCost(final Class<?>[] srcArgs, final Class<?>[] destArgs)
private static float getObjectTransformationCost(Class<?> srcClass, final Class<?> destClass)
private static float getPrimitivePromotionCost(final Class<?> srcClass, final Class<?> destClass)
