public void start() { [EOL]     if (this.runningState == STATE_STOPPED) { [EOL]         throw new IllegalStateException("Stopwatch must be reset before being restarted. "); [EOL]     } [EOL]     if (this.runningState != STATE_UNSTARTED) { [EOL]         throw new IllegalStateException("Stopwatch already started. "); [EOL]     } [EOL]     this.startTime = System.nanoTime(); [EOL]     this.startTimeMillis = System.currentTimeMillis(); [EOL]     this.runningState = STATE_RUNNING; [EOL] }
public void stop() { [EOL]     if (this.runningState != STATE_RUNNING && this.runningState != STATE_SUSPENDED) { [EOL]         throw new IllegalStateException("Stopwatch is not running. "); [EOL]     } [EOL]     if (this.runningState == STATE_RUNNING) { [EOL]         this.stopTime = System.nanoTime(); [EOL]     } [EOL]     this.runningState = STATE_STOPPED; [EOL] }
public void reset() { [EOL]     this.runningState = STATE_UNSTARTED; [EOL]     this.splitState = STATE_UNSPLIT; [EOL] }
public void split() { [EOL]     if (this.runningState != STATE_RUNNING) { [EOL]         throw new IllegalStateException("Stopwatch is not running. "); [EOL]     } [EOL]     this.stopTime = System.nanoTime(); [EOL]     this.splitState = STATE_SPLIT; [EOL] }
public void unsplit() { [EOL]     if (this.splitState != STATE_SPLIT) { [EOL]         throw new IllegalStateException("Stopwatch has not been split. "); [EOL]     } [EOL]     this.splitState = STATE_UNSPLIT; [EOL] }
public void suspend() { [EOL]     if (this.runningState != STATE_RUNNING) { [EOL]         throw new IllegalStateException("Stopwatch must be running to suspend. "); [EOL]     } [EOL]     this.stopTime = System.nanoTime(); [EOL]     this.runningState = STATE_SUSPENDED; [EOL] }
public void resume() { [EOL]     if (this.runningState != STATE_SUSPENDED) { [EOL]         throw new IllegalStateException("Stopwatch must be suspended to resume. "); [EOL]     } [EOL]     this.startTime += System.nanoTime() - this.stopTime; [EOL]     this.runningState = STATE_RUNNING; [EOL] }
public long getTime() { [EOL]     return getNanoTime() / NANO_2_MILLIS; [EOL] }
public long getNanoTime() { [EOL]     if (this.runningState == STATE_STOPPED || this.runningState == STATE_SUSPENDED) { [EOL]         return this.stopTime - this.startTime; [EOL]     } else if (this.runningState == STATE_UNSTARTED) { [EOL]         return 0; [EOL]     } else if (this.runningState == STATE_RUNNING) { [EOL]         return System.nanoTime() - this.startTime; [EOL]     } [EOL]     throw new RuntimeException("Illegal running state has occurred."); [EOL] }
public long getSplitTime() { [EOL]     return getSplitNanoTime() / NANO_2_MILLIS; [EOL] }
public long getSplitNanoTime() { [EOL]     if (this.splitState != STATE_SPLIT) { [EOL]         throw new IllegalStateException("Stopwatch must be split to get the split time. "); [EOL]     } [EOL]     return this.stopTime - this.startTime; [EOL] }
public long getStartTime() { [EOL]     if (this.runningState == STATE_UNSTARTED) { [EOL]         throw new IllegalStateException("Stopwatch has not been started"); [EOL]     } [EOL]     return this.startTimeMillis; [EOL] }
@Override [EOL] public String toString() { [EOL]     return DurationFormatUtils.formatDurationHMS(getTime()); [EOL] }
public String toSplitString() { [EOL]     return DurationFormatUtils.formatDurationHMS(getSplitTime()); [EOL] }
