public static double min(final double[] array)
public static float min(final float[] array)
public static double min(final double a, final double b, final double c)
public static double min(final double a, final double b)
public static float min(final float a, final float b, final float c)
public static float min(final float a, final float b)
public static double max(final double[] array)
public static float max(final float[] array)
public static double max(final double a, final double b, final double c)
public static double max(final double a, final double b)
public static float max(final float a, final float b, final float c)
public static float max(final float a, final float b)
