/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 04:46:26 GMT 2021
 */

package org.apache.commons.lang3.mutable;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.mutable.MutableObject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MutableObject_ESTest extends MutableObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MutableObject<String> mutableObject0 = new MutableObject<String>("org.apache.commons.lang3.mutable.MutableObject@0000000001");
      String string0 = mutableObject0.getValue();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MutableObject<Object> mutableObject0 = new MutableObject<Object>();
      Integer integer0 = new Integer((-61));
      MutableObject<Integer> mutableObject1 = new MutableObject<Integer>(integer0);
      mutableObject0.setValue(mutableObject1);
      MutableObject<MutableObject<Integer>> mutableObject2 = new MutableObject<MutableObject<Integer>>(mutableObject1);
      boolean boolean0 = mutableObject2.equals(mutableObject0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object object0 = new Object();
      MutableObject<MutableObject<String>> mutableObject0 = new MutableObject<MutableObject<String>>();
      boolean boolean0 = mutableObject0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MutableObject<Integer> mutableObject0 = new MutableObject<Integer>();
      boolean boolean0 = mutableObject0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer((-61));
      MutableObject<Integer> mutableObject0 = new MutableObject<Integer>(integer0);
      String string0 = mutableObject0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MutableObject<String> mutableObject0 = new MutableObject<String>();
      mutableObject0.hashCode();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MutableObject<Object> mutableObject0 = new MutableObject<Object>();
      Integer integer0 = new Integer((-61));
      MutableObject<Integer> mutableObject1 = new MutableObject<Integer>(integer0);
      mutableObject0.setValue(mutableObject1);
      mutableObject0.hashCode();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MutableObject<String> mutableObject0 = new MutableObject<String>();
      MutableObject<Object> mutableObject1 = new MutableObject<Object>();
      // Undeclared exception!
      try { 
        mutableObject1.equals(mutableObject0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MutableObject<MutableObject<Object>> mutableObject0 = new MutableObject<MutableObject<Object>>();
      MutableObject<Object> mutableObject1 = mutableObject0.getValue();
      assertNull(mutableObject1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MutableObject<MutableObject<Object>> mutableObject0 = new MutableObject<MutableObject<Object>>();
      MutableObject<Object> mutableObject1 = new MutableObject<Object>(mutableObject0);
      mutableObject0.setValue(mutableObject1);
      // Undeclared exception!
      try { 
        mutableObject1.equals(mutableObject0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MutableObject<Integer> mutableObject0 = new MutableObject<Integer>();
      String string0 = mutableObject0.toString();
      assertEquals("null", string0);
  }
}
